### ISSUE TITLE
Build fails on macOS Monterey

### ISSUE THREAD

**Issue by MartinCapraro** [lonski/eloxubur#1]
I can't get this to run.

If I try to compile it with `mix`, I get the following error:

```Generated ratatouille app
==> eloxubur
Compiling 6 files (.ex)
[asmjit] Assertion failed at aarch64-apple-darwin21.6.0/opt/jit/asmjit/core/../core/codeholder.h (line 911):
[asmjit] isLabelValid(labelId)
[1]    38799 abort      mix
```

If I try to run the tests with `mix test`, I get the following error:

```
13:22:00.244 [error] Error in application loop:
  ** (UndefinedFunctionError) function GameState.new/2 is undefined (module GameState is not available)
    GameState.new(76, 25)
    (ratatouille 0.4.1) lib/ratatouille/runtime.ex:155: Ratatouille.Runtime.initial_model/1
    (ratatouille 0.4.1) lib/ratatouille/runtime.ex:100: Ratatouille.Runtime.run/1
    (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.0) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**System details**
**OS:** macOS Monterey 12.6
**Hardware:** M1 Macbook Pro (16-inch, 2021)
**Erlang/OTP:** 25 [erts-13.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
**Elixir:** 1.14.0 (compiled with Erlang/OTP 25)

**Comment by MartinCapraro** [comment]
@lonski I've found a fix, it's pretty simple. I'm happy to create a pull request if you'd like to give me the necessary permissions?

**Comment by lonski** [comment]
Hi, you can just fork the project, implement changes and then raise pull request from your fork
